import React, { useState } from 'react';
import { Copy, Check, ExternalLink, Save, AlertCircle } from 'lucide-react';

interface QuickConfigUpdaterProps {
  onConfigUpdate?: (projectId: string, anonKey: string) => void;
}

export default function QuickConfigUpdater({ onConfigUpdate }: QuickConfigUpdaterProps) {
  const [projectId, setProjectId] = useState('');
  const [anonKey, setAnonKey] = useState('');
  const [copied, setCopied] = useState(false);

  const generateConfigCode = () => {
    if (!projectId || !anonKey) return '';
    
    return `/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "${projectId}"
export const publicAnonKey = "${anonKey}"

// Derived values
export const supabaseUrl = \`https://\${projectId}.supabase.co\`

// Utility function to validate API key format
export function validateApiKey(apiKey: string): boolean {
  if (!apiKey || typeof apiKey !== 'string') {
    return false;
  }
  
  // JWT tokens should start with "eyJ" and have at least 3 parts separated by dots
  if (!apiKey.startsWith('eyJ')) {
    return false;
  }
  
  const parts = apiKey.split('.');
  if (parts.length !== 3) {
    return false;
  }
  
  // Basic length check - valid JWTs are usually quite long
  if (apiKey.length < 100) {
    return false;
  }
  
  // Try to decode the header to verify it's a valid JWT structure
  try {
    const header = JSON.parse(atob(parts[0]));
    if (!header.alg || !header.typ) {
      return false;
    }
    return true;
  } catch (error) {
    return false;
  }
}

// Helper function to check if configuration is set up
export function isConfigured(): boolean {
  return projectId !== 'YOUR_NEW_PROJECT_ID' && publicAnonKey !== 'YOUR_NEW_ANON_KEY';
}

// Helper function to get configuration status
export function getConfigurationStatus(): {
  isConfigured: boolean;
  projectIdSet: boolean;
  anonKeySet: boolean;
  anonKeyValid: boolean;
} {
  const projectIdSet = projectId !== 'YOUR_NEW_PROJECT_ID';
  const anonKeySet = publicAnonKey !== 'YOUR_NEW_ANON_KEY';
  const anonKeyValid = anonKeySet && validateApiKey(publicAnonKey);
  
  return {
    isConfigured: projectIdSet && anonKeySet && anonKeyValid,
    projectIdSet,
    anonKeySet,
    anonKeyValid
  };
}`;
  };

  const copyToClipboard = async () => {
    const code = generateConfigCode();
    if (!code) return;

    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('复制失败:', err);
      alert('复制失败，请手动复制代码');
    }
  };

  const isValidApiKey = (key: string) => {
    return key.startsWith('eyJ') && key.split('.').length === 3 && key.length > 100;
  };

  const handleSave = () => {
    if (onConfigUpdate && projectId && anonKey) {
      onConfigUpdate(projectId, anonKey);
    }
    alert('配置信息已保存！请刷新页面以生效。');
  };

  const isFormValid = projectId.length > 0 && anonKey.length > 0 && isValidApiKey(anonKey);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-center">
        <h2 className="text-xl font-semibold text-gray-900 mb-2">快速配置 Supabase</h2>
        <p className="text-gray-600">输入您的项目信息，立即生成配置代码</p>
      </div>

      {/* Instructions */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <h3 className="font-medium text-blue-900 mb-2">📋 获取配置信息：</h3>
        <ol className="text-sm text-blue-800 space-y-1 list-decimal list-inside">
          <li>打开 <a href="https://app.supabase.com" target="_blank" rel="noopener noreferrer" className="underline inline-flex items-center">Supabase Dashboard <ExternalLink className="w-3 h-3 ml-1" /></a></li>
          <li>选择您的项目</li>
          <li>转到 Settings → General，复制 "Reference ID"</li>
          <li>转到 Settings → API，复制 "anon public" 密钥</li>
        </ol>
      </div>

      {/* Form */}
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            项目 Reference ID *
          </label>
          <input
            type="text"
            value={projectId}
            onChange={(e) => setProjectId(e.target.value.trim())}
            placeholder="例如: abcdefghijklmnop"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Anon/Public Key *
          </label>
          <textarea
            value={anonKey}
            onChange={(e) => setAnonKey(e.target.value.trim())}
            placeholder="eyJ..."
            rows={4}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
          />
          {anonKey && !isValidApiKey(anonKey) && (
            <div className="flex items-center space-x-1 mt-1 text-red-600">
              <AlertCircle className="w-4 h-4" />
              <span className="text-sm">API密钥格式不正确，应以 "eyJ" 开头</span>
            </div>
          )}
        </div>
      </div>

      {/* Generated Config Preview */}
      {isFormValid && (
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-medium text-gray-900">生成的配置代码</h3>
            <div className="flex space-x-2">
              <button
                onClick={copyToClipboard}
                className="flex items-center space-x-1 text-blue-600 hover:text-blue-800 text-sm bg-white px-3 py-1 rounded border border-blue-200 hover:border-blue-300 transition-colors"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                <span>{copied ? '已复制' : '复制代码'}</span>
              </button>
            </div>
          </div>
          
          <pre className="text-xs bg-white p-3 rounded border border-gray-200 max-h-60 overflow-y-auto font-mono">
            {generateConfigCode()}
          </pre>

          <div className="mt-3 p-3 bg-green-50 border border-green-200 rounded">
            <h4 className="text-sm font-medium text-green-900 mb-1">✅ 项目信息验证通过</h4>
            <div className="text-sm text-green-700 space-y-1">
              <p>• 项目URL: https://{projectId}.supabase.co</p>
              <p>• API密钥格式: 有效的JWT格式</p>
            </div>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex space-x-3">
        <button
          onClick={handleSave}
          disabled={!isFormValid}
          className="flex-1 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-300 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center space-x-2"
        >
          <Save className="w-4 h-4" />
          <span>保存配置</span>
        </button>
      </div>

      {/* Next Steps */}
      {isFormValid && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
          <h3 className="font-medium text-amber-900 mb-2">📝 下一步操作：</h3>
          <ol className="text-sm text-amber-800 space-y-1 list-decimal list-inside">
            <li>将生成的代码保存到 <code className="bg-amber-200 px-1 rounded">/utils/supabase/info.tsx</code> 文件</li>
            <li>在Supabase Dashboard的SQL Editor中运行数据库迁移脚本</li>
            <li>设置Edge Function环境变量</li>
            <li>测试连接和功能</li>
          </ol>
        </div>
      )}
    </div>
  );
}