import React, { useState, useEffect } from 'react';
import { CheckCircle, AlertCircle, Copy, ExternalLink, Play, Loader2, Database, Key, Cloud, Settings } from 'lucide-react';

interface SetupStep {
  id: string;
  title: string;
  description: string;
  status: 'pending' | 'in-progress' | 'completed' | 'error';
  action?: () => void;
}

export default function SupabaseSetupWizard() {
  const [projectId, setProjectId] = useState('');
  const [anonKey, setAnonKey] = useState('');
  const [serviceKey, setServiceKey] = useState('');
  const [isValidating, setIsValidating] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [setupStatus, setSetupStatus] = useState<{[key: string]: 'pending' | 'completed' | 'error'}>({});

  const steps: SetupStep[] = [
    {
      id: 'project-info',
      title: '项目信息配置',
      description: '输入您的Supabase项目ID和API密钥',
      status: projectId && anonKey ? 'completed' : 'pending'
    },
    {
      id: 'validate-connection',
      title: '验证连接',
      description: '测试与Supabase项目的连接',
      status: setupStatus.connection || 'pending',
      action: validateConnection
    },
    {
      id: 'database-setup',
      title: '数据库设置',
      description: '创建所需的数据表和权限',
      status: setupStatus.database || 'pending',
      action: setupDatabase
    },
    {
      id: 'storage-setup',
      title: '存储配置',
      description: '设置图片存储桶和权限',
      status: setupStatus.storage || 'pending',
      action: setupStorage
    },
    {
      id: 'edge-functions',
      title: 'Edge Functions',
      description: '部署服务器端函数',
      status: setupStatus.functions || 'pending',
      action: setupEdgeFunctions
    }
  ];

  async function validateConnection() {
    if (!projectId || !anonKey) {
      alert('请先填写项目ID和API密钥');
      return;
    }

    setIsValidating(true);
    try {
      const testUrl = `https://${projectId}.supabase.co/rest/v1/`;
      const response = await fetch(testUrl, {
        method: 'HEAD',
        headers: {
          'apikey': anonKey,
          'Authorization': `Bearer ${anonKey}`
        }
      });

      if (response.ok) {
        setSetupStatus(prev => ({ ...prev, connection: 'completed' }));
        alert('✅ 连接验证成功！');
      } else {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
    } catch (error: any) {
      setSetupStatus(prev => ({ ...prev, connection: 'error' }));
      alert(`❌ 连接失败: ${error.message}`);
    }
    setIsValidating(false);
  }

  async function setupDatabase() {
    alert('请在Supabase Dashboard的SQL Editor中运行数据库迁移脚本。\n\n步骤：\n1. 打开 Supabase Dashboard\n2. 转到 SQL Editor\n3. 依次运行 001_initial_setup.sql 和 002_add_language_support.sql');
    setSetupStatus(prev => ({ ...prev, database: 'completed' }));
  }

  async function setupStorage() {
    alert('存储桶将通过数据库脚本自动创建。如果遇到问题，请在Storage页面手动创建名为 "make-55b791b3-portfolio-assets" 的公共存储桶。');
    setSetupStatus(prev => ({ ...prev, storage: 'completed' }));
  }

  async function setupEdgeFunctions() {
    alert('请按照以下步骤部署Edge Functions：\n\n1. 在Edge Functions → Settings中设置环境变量\n2. 使用Supabase CLI部署函数\n\n详细步骤请参考ENVIRONMENT_VARIABLES.md文件。');
    setSetupStatus(prev => ({ ...prev, functions: 'completed' }));
  }

  const generateConfigCode = () => {
    if (!projectId || !anonKey) return '';
    
    // Create the configuration code as a string
    const configCode = [
      '/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */',
      '',
      `export const projectId = "${projectId}"`,
      `export const publicAnonKey = "${anonKey}"`,
      '',
      '// Derived values',
      'export const supabaseUrl = `https://${projectId}.supabase.co`',
      '',
      '// Utility function to validate API key format',
      'export function validateApiKey(apiKey: string): boolean {',
      '  if (!apiKey || typeof apiKey !== \'string\') {',
      '    return false;',
      '  }',
      '  ',
      '  // JWT tokens should start with "eyJ" and have at least 3 parts separated by dots',
      '  if (!apiKey.startsWith(\'eyJ\')) {',
      '    return false;',
      '  }',
      '  ',
      '  const parts = apiKey.split(\'.\');',
      '  if (parts.length !== 3) {',
      '    return false;',
      '  }',
      '  ',
      '  // Basic length check - valid JWTs are usually quite long',
      '  if (apiKey.length < 100) {',
      '    return false;',
      '  }',
      '  ',
      '  // Try to decode the header to verify it\'s a valid JWT structure',
      '  try {',
      '    const header = JSON.parse(atob(parts[0]));',
      '    if (!header.alg || !header.typ) {',
      '      return false;',
      '    }',
      '    return true;',
      '  } catch (error) {',
      '    return false;',
      '  }',
      '}',
      '',
      '// Helper function to check if configuration is set up',
      'export function isConfigured(): boolean {',
      '  return projectId !== \'YOUR_NEW_PROJECT_ID\' && publicAnonKey !== \'YOUR_NEW_ANON_KEY\';',
      '}',
      '',
      '// Helper function to get configuration status',
      'export function getConfigurationStatus(): {',
      '  isConfigured: boolean;',
      '  projectIdSet: boolean;',
      '  anonKeySet: boolean;',
      '  anonKeyValid: boolean;',
      '} {',
      '  const projectIdSet = projectId !== \'YOUR_NEW_PROJECT_ID\';',
      '  const anonKeySet = publicAnonKey !== \'YOUR_NEW_ANON_KEY\';',
      '  const anonKeyValid = anonKeySet && validateApiKey(publicAnonKey);',
      '  ',
      '  return {',
      '    isConfigured: projectIdSet && anonKeySet && anonKeyValid,',
      '    projectIdSet,',
      '    anonKeySet,',
      '    anonKeyValid',
      '  };',
      '}'
    ].join('\n');
    
    return configCode;
  };

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      alert('已复制到剪贴板！');
    } catch (err) {
      console.error('复制失败:', err);
      alert('复制失败，请手动复制');
    }
  };

  const getStepIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return <CheckCircle className="w-5 h-5 text-green-600" />;
      case 'error':
        return <AlertCircle className="w-5 h-5 text-red-600" />;
      case 'in-progress':
        return <Loader2 className="w-5 h-5 text-blue-600 animate-spin" />;
      default:
        return <div className="w-5 h-5 rounded-full border-2 border-gray-300" />;
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-8">
      {/* Header */}
      <div className="text-center">
        <div className="flex items-center justify-center space-x-2 mb-4">
          <Cloud className="w-8 h-8 text-blue-600" />
          <h1 className="text-2xl font-bold text-gray-900">Supabase 设置向导</h1>
        </div>
        <p className="text-gray-600">按照步骤配置您的Supabase项目，确保所有功能正常工作</p>
      </div>

      {/* Step 1: Project Configuration */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <Key className="w-6 h-6 text-blue-600" />
            <h2 className="text-lg font-semibold text-gray-900">步骤 1: 项目信息配置</h2>
          </div>
          <p className="text-sm text-gray-600 mt-2">
            请从您的Supabase Dashboard → Settings → API 页面获取以下信息
          </p>
        </div>

        <div className="p-6 space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              项目 Reference ID
            </label>
            <input
              type="text"
              value={projectId}
              onChange={(e) => setProjectId(e.target.value.trim())}
              placeholder="例如: abcdefghijklmnop"
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            <p className="text-xs text-gray-500 mt-1">
              在 Settings → General 中找到 "Reference ID"
            </p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Anon/Public Key
            </label>
            <textarea
              value={anonKey}
              onChange={(e) => setAnonKey(e.target.value.trim())}
              placeholder="eyJ..."
              rows={3}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
            />
            <p className="text-xs text-gray-500 mt-1">
              在 Settings → API 中找到 "anon public" 密钥
            </p>
          </div>

          {projectId && anonKey && (
            <div className="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg">
              <h3 className="text-sm font-medium text-green-900 mb-2">✅ 配置信息已填写</h3>
              <p className="text-sm text-green-700 mb-3">
                项目URL: https://{projectId}.supabase.co
              </p>
              
              {/* Generated Config */}
              <div className="bg-white rounded border border-green-200 p-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium text-gray-700">生成的配置代码:</span>
                  <button
                    onClick={() => copyToClipboard(generateConfigCode())}
                    className="flex items-center space-x-1 text-blue-600 hover:text-blue-800 text-sm"
                  >
                    <Copy className="w-4 h-4" />
                    <span>复制</span>
                  </button>
                </div>
                <pre className="text-xs bg-gray-50 p-2 rounded border max-h-40 overflow-y-auto">
                  {generateConfigCode()}
                </pre>
              </div>
              
              <p className="text-xs text-green-600 mt-2">
                💡 请将上面的代码保存到 /utils/supabase/info.tsx 文件中
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Steps Progress */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <Settings className="w-6 h-6 text-blue-600" />
            <h2 className="text-lg font-semibold text-gray-900">设置进度</h2>
          </div>
        </div>

        <div className="p-6">
          <div className="space-y-4">
            {steps.map((step, index) => (
              <div key={step.id} className="flex items-center space-x-4 p-4 border border-gray-200 rounded-lg">
                <div className="flex-shrink-0">
                  {getStepIcon(step.status)}
                </div>
                <div className="flex-1">
                  <h3 className="font-medium text-gray-900">{step.title}</h3>
                  <p className="text-sm text-gray-600">{step.description}</p>
                </div>
                {step.action && (
                  <button
                    onClick={step.action}
                    disabled={step.status === 'completed' || (index === 1 && (!projectId || !anonKey))}
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center space-x-2 text-sm"
                  >
                    <Play className="w-4 h-4" />
                    <span>执行</span>
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Database Scripts */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <Database className="w-6 h-6 text-blue-600" />
            <h2 className="text-lg font-semibold text-gray-900">数据库迁移脚本</h2>
          </div>
          <p className="text-sm text-gray-600 mt-2">
            请在Supabase Dashboard的SQL Editor中按顺序运行以下脚本
          </p>
        </div>

        <div className="p-6 space-y-4">
          <div className="space-y-3">
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <div>
                <span className="font-medium text-gray-900">1. 初始设置脚本</span>
                <p className="text-sm text-gray-600">创建基础表结构和权限</p>
              </div>
              <div className="flex space-x-2">
                <span className="text-sm text-gray-500">/supabase/migrations/001_initial_setup.sql</span>
                <a
                  href="https://app.supabase.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-800"
                >
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </div>

            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <div>
                <span className="font-medium text-gray-900">2. 语言支持脚本</span>
                <p className="text-sm text-gray-600">添加多语言功能</p>
              </div>
              <div className="flex space-x-2">
                <span className="text-sm text-gray-500">/supabase/migrations/002_add_language_support.sql</span>
                <a
                  href="https://app.supabase.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-800"
                >
                  <ExternalLink className="w-4 h-4" />
                </a>
              </div>
            </div>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="font-medium text-blue-900 mb-2">如何运行脚本:</h4>
            <ol className="text-sm text-blue-800 space-y-1">
              <li>1. 打开 <a href="https://app.supabase.com" target="_blank" rel="noopener noreferrer" className="underline">Supabase Dashboard</a></li>
              <li>2. 选择您的项目</li>
              <li>3. 转到 SQL Editor 页面</li>
              <li>4. 创建新查询，复制粘贴第一个脚本内容</li>
              <li>5. 点击 "Run" 执行</li>
              <li>6. 重复步骤4-5执行第二个脚本</li>
            </ol>
          </div>
        </div>
      </div>

      {/* Help */}
      <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
        <h3 className="font-medium text-gray-900 mb-3">需要帮助？</h3>
        <div className="text-sm text-gray-700 space-y-2">
          <p>• 如果遇到问题，请查看项目根目录的各种设置指南文件</p>
          <p>• 确保在Supabase Dashboard中正确设置了环境变量</p>
          <p>• 验证所有API密钥都是正确且最新的</p>
          <p>• 如果Edge Function部署失败，请检查Supabase CLI是否已正确安装</p>
        </div>
      </div>
    </div>
  );
}